### ISSUE TITLE
extract_event_ranges

### ISSUE THREAD

**Issue by jtmbeta** [beOn/cili#2]
Hi there

This code is great. I was just wondering what the annoying assumption is in the extract_event_ranges function. Is it a sampling rate of 1000Hz, or is it that all ranges are equal in length?

 I'm trying to extract ranges with variable lengths. I thought I would ask if there is a simple way of doing this before I barge in and break the code.

Many thanks
Joel

![image](https://cloud.githubusercontent.com/assets/11196943/6375924/5736021a-bd12-11e4-8dc0-71fe2807f2c6.png)

**Comment by beOn** [comment]
Ah, I should have said what the assumption was... I'm pretty sure this is referring to the same thing as the comment three lines above - the assumption being that the number of samples per range is always the same. That isn't so great. If you have hacked around the issue already, I'd be happy to look through a pull request! Otherwise, let me know what you're trying to do (sample data and sample code, or a good description at least) and I'll take a look!

**Comment by beOn** [comment]
The assumption was that every range start time would be available in the samples, which is true in 1kHz data, but not necessarily for other frequencies. See Issue #3 for more discussion of this, and the ongoing effort to deal with it (should be wrapped up soon).

W.r.t. the other issue - wanting to extract ranges of different lengths, open up a feature request and let's get rolling on that.
